global:
  marketplace: true
  owner: quickstart-eng@amazon.com
  qsname: quickstart-datastax
  regions:
    - eu-central-1
    - us-west-2
  reporting: true
tests:
  datastax:
    parameter_input: quickstart-datastax-taskcat.json
    template_file: quickstart-datastax-master.template
    regions:
    - us-central-2
    - eu-west-1
