global:
  marketplace: true
  owner: quickstart-eng@amazon.com
  qsname: quickstart-datastax
  regions:
    - us-east-1
  reporting: true
tests:
  datastax:
    parameter_input: quickstart-datastax-taskcat.json
    template_file: quickstart-datastax-master.template
    regions:
    - us-east-1